[phases]
  [phases.frontend]
  directory = "frontend"
  command = "npm install && npm run build"

  [phases.backend]
  directory = "backend"
  command = "yarn add"

[cmd]
start = "cd backend && yarn start"
